#!/bin/sh
###############################################################################
#
#VARS INIT
#
###############################################################################
JAVA_HOME=/usr/local/java
DIR_DOWNLOAD=/tmp/download.$$
DIR_NEW_JDK=jdk1.8.0_172

JDK_TAR_GZ=jdk-8u172-linux-x64.tar.gz
JDK_URL="http://download.oracle.com/otn-pub/java/jdk/8u172-b11/a58eab1ec242421181065cdc37240b08/${JDK_TAR_GZ}"

PROFILES=/etc/profile


###############################################################################
#
#DOWNLOAD JDK & MAVEN
#
###############################################################################
mkdir -p ${DIR_DOWNLOAD}
cd $DIR_DOWNLOAD
date
echo "## Download begins : JDK : ${JDK_TAR_GZ}"
wget --header "Cookie: oraclelicense=accept-securebackup-cookie" ${JDK_URL} >/dev/null 2>&1
echo "## Download ends   : JDK : ${JDK_TAR_GZ}"
echo

echo "## Check download"
ls -l ${JDK_TAR_GZ} 

###############################################################################
#
#INSTALL JDK & MAVEN
#
###############################################################################
#create directories
mkdir -p ${JAVA_HOME}

date
echo "## Install begins : JDK : {JAVA_HOME}"
cd ${JAVA_HOME}
gunzip -c ${DIR_DOWNLOAD}/${JDK_TAR_GZ} | tar xvf -
echo "## Install ends   : JDK : {JAVA_HOME}"
echo

###############################################################################
#
#ENVIRONMENT VARS
#
###############################################################################
echo "## Env setting : JDK : JAVA_HOME + PATH"
echo "" >>${PROFILES}
echo "#JDK Setting" >>${PROFILES}
echo "export JAVA_HOME=${JAVA_HOME}/${DIR_NEW_JDK}" >>${PROFILES}
echo "export PATH=\${JAVA_HOME}/bin:\$PATH" >>${PROFILES}
export JAVA_HOME=${JAVA_HOME}/${DIR_NEW_JDK}
export export PATH=${JAVA_HOME}/bin:$PATH

###############################################################################
#
#CONFIRM VERSION
#
###############################################################################
echo "## Check Java version"
java -version
echo


###############################################################################
#
#REMOVE DOWNLOAD FILES
#
###############################################################################
echo "## Delete Download files"
rm -rf ${DIR_DOWNLOAD}
date
